### PR TITLE
Build attraction page

### PR DESCRIPTION
**Pull request by chelsey0527**
李沁珊
http://18.180.11.43:3000/
http://18.180.11.43:3000/attraction/10

### CODE REVIEW

**Review by cwpeng — CHANGES_REQUESTED** [review]
1. Color, margins.
2. Aspect ratio of any images in your page should keep the same as original ones.
3. Image slider should extend to full width and keep no margin space with navigator bar.
18 180 11 43_3000_attraction_1

**Comment by chelsey0527** [comment]
1. Set color for a in nav , rearrange margins between containers.
2. using fixed ratio
3. Image slider should extend to full width 
4. remove image slider's margin space with navigator bar.

**Comment by cwpeng** [comment]
Re-request review so that I can review for you.

**Review by cwpeng — CHANGES_REQUESTED** [review]
Image slider should extend to full width and keep no margin space with navigator bar in mobile version.
18 180 11 43_3000_attraction_10

**Pull request merged**
