### PR TITLE
Build attraction APIs

### PR DESCRIPTION
**Pull request by chelsey0527**
姓名：李沁珊
DC：邱西
http://18.180.11.43:3000/api/attractions?page=1
http://18.180.11.43:3000/api/attractions?page=0&keyword=%E8%97%9D%E6%96%87%E9%A4%A8%E6%89%80
http://18.180.11.43:3000/api/attractions?page=0&keyword=%E5%8C%97
http://18.180.11.43:3000/api/attraction/10

### CODE REVIEW

**Review by cwpeng — CHANGES_REQUESTED** [review]
1. Response formats of all of your APIs are incorrect.
2. `"null"` is not `null`.

Solve issues and re-request review.

**Comment by chelsey0527** [comment]
姓名：李沁珊
DC：邱西
http://18.180.11.43:3000/api/attractions?page=1
http://18.180.11.43:3000/api/attractions?page=0&keyword=%E8%97%9D%E6%96%87%E9%A4%A8%E6%89%80
http://18.180.11.43:3000/api/attractions?page=0&keyword=%E5%8C%97
http://18.180.11.43:3000/api/attraction/10

1. Modify formats ( including jsonify sequence, the way I append data results)
2. Change "null" into None

**Comment by cwpeng** [comment]
Re-request review from reviewers section in the right side of this page, so that I can review for you.

**Review by cwpeng — APPROVED** [review]
OK. Done.

**Pull request merged**
