### PR TITLE
Develop booking

### PR DESCRIPTION
**Pull request by chelsey0527**
李沁珊
http://18.180.11.43:3000/
http://18.180.11.43:3000/attraction/4
http://18.180.11.43:3000/booking

### CODE REVIEW

**Review by cwpeng — CHANGES_REQUESTED** [review]
1. We will not show sign in/up dialog immediately after loading attraction page.
2. Too much top and bottom margin space for title of booking page.
18 180 11 43_3000_booking

**Review by cwpeng — CHANGES_REQUESTED** [review]
I cannot delete reserved attraction in booking page.

**Comment by chelsey0527** [comment]
I do not see any malfunction, please check the following screenshots.
截圖 2022-12-16 16 46 22
截圖 2022-12-16 16 46 27

**Comment by cwpeng** [comment]
OK. I tried again and everything is fine. But your lines are too close in the booking page without attractions. Fix this small issue and re-request review.

**Review by cwpeng — COMMENTED** [review]
I see no changes there.
18 180 11 43_3000_booking

**Comment by chelsey0527** [comment]
Sorry, forgot to pull repo on ec2 server.
Please check again.

**Review by cwpeng — APPROVED** [review]
OK. Done.

**Pull request merged**
